[project]
name = "switchbotopenapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openapi-core>=0.19.4",
    "openapi-spec-validator>=0.7.1",
    "pytest>=8.3.4",
]
